
[click_gui]

	[click_gui.___]
		combatx = 45.5
		combaty = 8.0

[macro]
	"&cchest_stealer" = false
	"&cskull_aura" = false
	"&clever_aura" = false
	"&csword_swap" = false
	"&cchest_aura" = false

	[macro.__]
		"&csnowball_swap" = false
		"&cfishing_rod_swap" = false

	[macro.___]
		"&cauction_sniper" = false
		"&cauction_sniper_p2" = true

	[macro._]
		"&cscaffold" = false

[other]

	[other.__]
		"&2mushroom_rainbow" = false
		"&bmushroom_client_text" = false
		"&cmushroom_client_on_top" = false
		"&9mushroom_shadow" = false
		"&amushroom_client_logo" = false

	[other.____]
		"&aclick_for_updates!" = true
		"&3funny_score_calc" = true
		"&c270_score_message" = "lunar client > 269 score"
		"&3p3_ghostblocks" = true
		"&3dungeon_score_calc" = true
		"&c300_score_message" = "lunar client > 269 score"

	[other.___]
		"&cdiscord_rpc_bottom_text" = "NO im not silly! GRRRRRRRR"
		"&cdiscord_rpc_text" = "HIII scale"
		combatx = 58.5
		combaty = 5.5
		"&ddiscord_rpc_picture" = 6
		"&3discord_rpc" = true
		"&3discord_rpc_location" = true

	[other._]
		"&cs&ep&ca&en&ci&es&ch" = false
		"&chilarity" = true
		"&comega_hilarity" = false
		"&clarge_hilarity" = false
		"&ahilarity" = true
		"&cspanish_translator" = false
		"&4large_hilarity" = false

[chat_macro]
	"&bguild_bridge_bots_name" = "DefyBridge"
	"&aguild_bot" = true
	"&awelcome_guild!!!" = true
	"&aguild_bridge_bot" = false
	"&cguild_bridge_bot" = true
	"&cguild_bot" = true
	"&cwelcome_guild!!!" = true
	"&cguild_bridge_bots_name" = ""
	"&bwelcome_guild_message" = "Good morning player how are you"
	"&awelcome_guild_message_part_2" = "how are you doing?"
	"&cwelcome_guild_message" = "Good morning"

	[chat_macro.__]
		"&cgeneral_quickmaths" = true
		quotes_pog = false
		"&cauto_send_quickmaths_answer" = true
		"&aquickmaths_solver!" = true
		"&cquickmaths_solver!" = true
		"&cquotes_pog" = true

	[chat_macro.______]
		"&5self_death_message" = "TANKS FAULT! OMFG WHY IS HE NOT NEAR ME WHERES THE HEALER MAN PLEASE MASTIFF WISH AND WHY IS NO ONE CLEARING MY ROOMS FOR ME YOUR ALL THROWING"
		"&cl_guy_died!" = true
		"&cdeath_message" = "OMG LOOK AT THIS NON! player has died! BAD"

	[chat_macro.____]
		"&dauto_party_transfer" = false
		"&cauto_party_transfer" = true

	[chat_macro.___]
		"&c\"wrong_chat\"" = true
		"&c\"gg\"" = true
		"&5\"wrong_chat\"" = false
		"&b\"gg\"" = false
		"&b\"gg\"_in_guild_chat" = false
		"&c\"wrong_chat\"_in_guild_chat" = true
		"&5\"wrong_chat\"_in_guild_chat" = false
		"&c\"gg\"_in_party_chat" = true
		"&5\"wrong_chat\"_in_party_chat" = false
		"&b\"gg\"_in_party_chat" = false
		"&c\"gg\"_in_guild_chat" = true
		"&c\"wrong_chat\"_in_party_chat" = true

	[chat_macro._]
		"&18ball" = true
		"&1guild_maths_bot" = true
		"&cball" = true
		"&cguild_maths_bot" = true

[keybind]

	[keybind.___]
		antikb_keybind = "   \\"
		nowall_keybind = "  \\"
		autoblock_keybind = "   \\"
		freeze_keybind = 1.0
		killaura_keybind = "   \\"
		cpsmultiplier_keybind = "   \\"

[skyblock]
	"&3autoharp" = false
	"&3auto_kick_shitters" = false
	"&cauto_kick_shitters" = false
	"&cdungeon_score_calc" = false
	"&3shitter_warning" = false
	"&3dungeon_score_calc_message" = true
	"&cdungeon_score_calc_message" = true
	"&cshitter_warning" = true
	"&fautoharp" = true
	"&3funny_score_calc" = false
	"&cfunny_score_calc" = true
	"&3dungeon_score_calc" = false

	[skyblock.__]
		"&3autoharp" = true
		"&3autoterms" = false
		"&cautoterms" = true
		ghostblocks = false
		"&c_ghostblocks" = false
		"&3p3_ghostblocks" = true

	[skyblock.______]
		"&5self_death_message" = "TANKS FAULT! OMFG WHY IS HE NOT NEAR ME WHERES THE HEALER MAN PLEASE MASTIFF WISH AND WHY IS NO ONE CLEARING MY ROOMS FOR ME YOUR ALL THROWING"
		"&cself_death_message" = "TANKS FAULT! OMFG WHY IS HE NOT NEAR ME WHERES THE HEALER MAN PLEASE MASTIFF WISH AND WHY IS NO ONE CLEARING MY ROOMS FOR ME YOUR ALL THROWING"
		"&c_guy_died!" = true
		"&cl_guy_died!" = false
		"&cdeath_message" = "OMG LOOK AT THIS NON! player has died! BAD"

	[skyblock.___]
		"&3autoharp" = true
		"&cauction_sniper" = false
		"&cm6_gyro_times_for_mage" = false
		"&cauction_sniper_p2" = false
		"&3titanium_esp" = true
		"&c_gyro_times_for_mage" = false

	[skyblock._]
		"&c270_score_message" = "lunar client > 269 score"
		"&c300_score_message" = "this could be us but you playin: https://imgur.com/X4ekG2U"

[visual]
	"&aesp_color" = "255,0,255,0"
	"&cplayer_esp" = false
	"&citem_esp" = false
	"&cesp_armorstands" = false
	"&cclick_gui" = true
	"&cskull_esp" = false
	"&cchest_esp" = false
	"&centity_esp" = true
	"&fesp_color" = "255,0,255,0"
	"&cblock_esp" = false

	[visual.__]
		"&cfakeban_time" = 0
		"&cfakeban_type" = 0
		"&afakeban_time" = 1
		"&5custom_fakeban_reason" = "Cheating through the use of unfair game advantages."
		"&cbeamed" = false
		"&4custom_fakeban_perm" = false
		beamed = false
		"&ccustom_fakeban_time" = "4d 2h 0m 6s"
		"&ccustom_fakeban_reason" = "Heckering cheter gat bend"
		"&ccustom_fakeban_perm" = false
		"&dfakeban_type" = 5
		"&ecustom_fakeban_time" = "29d 23h 55m 29s"

	[visual._]
		"&cfakename" = true
		"&bfake_rank_you_want_to_show" = "&epenis"
		"&cfake_rank_you_want_to_show" = "§c§lM§f§lu§c§ls§f§lh§c§lr§f§lo§c§lo§f§lo§c§lm §lClient§f§l"
		"&3fakename" = true
		"&bfake_name_you_want_to_show" = "&dSwog"
		"&3cfakename" = true
		"&cfake_name_you_want_to_show" = "[&bSwog&f]&4Swig"

[combat]
	"&cleft_click_cps_multiplier" = false
	"&cfreeze_(use_caution)" = false
	freeze = false
	"freeze_(use_caution)" = false
	"&cright_click_cps_multiplier" = false
	"&ccps_multiplier" = false

	[combat.__]
		"&cno_walls" = false
		"&creach" = false
		"&ckillaura_through_walls" = true
		"&ckillaura_mobs" = false
		"&ckillaura_autoblock" = true
		"&ckillaura" = false
		"&canti_knockback" = false

	[combat._]
		"&cautoblock" = false

[sliders]
	"&cping" = 200
	"&chilarity_speed" = 1000
	"&4hilarity_speed" = 1462

	[sliders.____]
		"&4autoterm_speed" = 1
		"&4left_click_auto_clicker_speed" = 20
		"&cautoterm_speed" = 200

	[sliders.___]
		"&4right_click_auto_clicker_speed" = 30
		"&cleft_click_auto_clicker_speed" = 20
		"&czombies_gun_macro_speed" = 500
		"&4left_click_auto_clicker_speed" = 20
		"&cright_click_auto_clicker_speed" = 20
		"&4zombies_gun_macro_speed" = 500

	[sliders._]
		"&cskull_aura_reach" = 5
		"&clever_aura_reach" = 5
		"&cquickmaths_solver_speed" = 50
		"&bquickmaths_solver_speed" = 155
		"&cchest_aura_reach" = 5

[cosmetics]

	[cosmetics.__]
		"&duwu_mommy_cape" = false
		"&lrgb_names" = false

	[cosmetics._]
		"&lput_rgb_name_here" = "&d&lIfallAddons§f§l"

